(cl:in-package sagittarius_openclaw_bridge-srv)
(cl:export '(COMMAND-VAL
          COMMAND
          COLOR-VAL
          COLOR
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          USE_RPY-VAL
          USE_RPY
          SUCCESS-VAL
          SUCCESS
          RESULT_CODE-VAL
          RESULT_CODE
          MESSAGE-VAL
          MESSAGE
          DETECTED_COLOR-VAL
          DETECTED_COLOR
          TARGET_X-VAL
          TARGET_X
          TARGET_Y-VAL
          TARGET_Y
          TARGET_Z-VAL
          TARGET_Z
))