//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the sagittarius_object_color_detector package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __sagittarius_object_color_detector__HSVPARAMSCONFIG_H__
#define __sagittarius_object_color_detector__HSVPARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace sagittarius_object_color_detector
{
  class HSVParamsConfigStatics;

  class HSVParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(HSVParamsConfig &config, const HSVParamsConfig &max, const HSVParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const HSVParamsConfig &config1, const HSVParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, HSVParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const HSVParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, HSVParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const HSVParamsConfig &config) const = 0;
      virtual void getValue(const HSVParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T HSVParamsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T HSVParamsConfig::* field;

      virtual void clamp(HSVParamsConfig &config, const HSVParamsConfig &max, const HSVParamsConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const HSVParamsConfig &config1, const HSVParamsConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, HSVParamsConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const HSVParamsConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, HSVParamsConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const HSVParamsConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const HSVParamsConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, HSVParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, HSVParamsConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<HSVParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(HSVParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("HSV_Enable"==(*_i)->name){HSV_Enable = boost::any_cast<bool>(val);}
        if("color_type"==(*_i)->name){color_type = boost::any_cast<int>(val);}
      }
    }

    bool HSV_Enable;
int color_type;

    bool state;
    std::string name;

    class HSV_PARAMS
{
  public:
    HSV_PARAMS()
    {
      state = true;
      name = "HSV_Params";
    }

    void setParams(HSVParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("H_Max"==(*_i)->name){H_Max = boost::any_cast<int>(val);}
        if("H_Min"==(*_i)->name){H_Min = boost::any_cast<int>(val);}
        if("S_Max"==(*_i)->name){S_Max = boost::any_cast<int>(val);}
        if("S_Min"==(*_i)->name){S_Min = boost::any_cast<int>(val);}
        if("V_Max"==(*_i)->name){V_Max = boost::any_cast<int>(val);}
        if("V_Min"==(*_i)->name){V_Min = boost::any_cast<int>(val);}
      }
    }

    int H_Max;
int H_Min;
int S_Max;
int S_Min;
int V_Max;
int V_Min;

    bool state;
    std::string name;

    class RED_HUE_EXTENSION
{
  public:
    RED_HUE_EXTENSION()
    {
      state = true;
      name = "red_Hue_Extension";
    }

    void setParams(HSVParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("H_Extend"==(*_i)->name){H_Extend = boost::any_cast<int>(val);}
      }
    }

    int H_Extend;

    bool state;
    std::string name;

    
}red_hue_extension;

}hsv_params;

}groups;



//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool HSV_Enable;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int color_type;
//#line 11 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      int H_Max;
//#line 12 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      int H_Min;
//#line 13 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      int S_Max;
//#line 14 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      int S_Min;
//#line 15 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      int V_Max;
//#line 16 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      int V_Min;
//#line 18 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      int H_Extend;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("HSVParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const HSVParamsConfig &__max__ = __getMax__();
      const HSVParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const HSVParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const HSVParamsConfig &__getDefault__();
    static const HSVParamsConfig &__getMax__();
    static const HSVParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const HSVParamsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void HSVParamsConfig::ParamDescription<std::string>::clamp(HSVParamsConfig &config, const HSVParamsConfig &max, const HSVParamsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class HSVParamsConfigStatics
  {
    friend class HSVParamsConfig;

    HSVParamsConfigStatics()
    {
HSVParamsConfig::GroupDescription<HSVParamsConfig::DEFAULT, HSVParamsConfig> Default("Default", "", 0, 0, true, &HSVParamsConfig::groups);
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.HSV_Enable = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.HSV_Enable = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.HSV_Enable = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<bool>("HSV_Enable", "bool", 0, "Output HSV Filter", "", &HSVParamsConfig::HSV_Enable)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<bool>("HSV_Enable", "bool", 0, "Output HSV Filter", "", &HSVParamsConfig::HSV_Enable)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.color_type = -2147483648;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.color_type = 2147483647;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.color_type = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("color_type", "int", 0, "Cube Color", "{'enum': [{'name': 'blue', 'type': 'int', 'value': 0, 'srcline': 24, 'srcfile': '/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg', 'description': '', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'green', 'type': 'int', 'value': 1, 'srcline': 25, 'srcfile': '/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg', 'description': '', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'red', 'type': 'int', 'value': 2, 'srcline': 26, 'srcfile': '/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg', 'description': '', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'customize', 'type': 'int', 'value': 3, 'srcline': 27, 'srcfile': '/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg', 'description': '', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'color type'}", &HSVParamsConfig::color_type)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("color_type", "int", 0, "Cube Color", "{'enum': [{'name': 'blue', 'type': 'int', 'value': 0, 'srcline': 24, 'srcfile': '/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg', 'description': '', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'green', 'type': 'int', 'value': 1, 'srcline': 25, 'srcfile': '/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg', 'description': '', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'red', 'type': 'int', 'value': 2, 'srcline': 26, 'srcfile': '/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg', 'description': '', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'customize', 'type': 'int', 'value': 3, 'srcline': 27, 'srcfile': '/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg', 'description': '', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'color type'}", &HSVParamsConfig::color_type)));
HSVParamsConfig::GroupDescription<HSVParamsConfig::DEFAULT::HSV_PARAMS, HSVParamsConfig::DEFAULT> HSV_Params("HSV_Params", "", 0, 1, true, &HSVParamsConfig::DEFAULT::hsv_params);
//#line 11 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __min__.H_Max = 0;
//#line 11 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __max__.H_Max = 360;
//#line 11 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __default__.H_Max = 360;
//#line 11 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      HSV_Params.abstract_parameters.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("H_Max", "int", 0, "Hue Max", "", &HSVParamsConfig::H_Max)));
//#line 11 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __param_descriptions__.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("H_Max", "int", 0, "Hue Max", "", &HSVParamsConfig::H_Max)));
//#line 12 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __min__.H_Min = 0;
//#line 12 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __max__.H_Min = 360;
//#line 12 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __default__.H_Min = 0;
//#line 12 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      HSV_Params.abstract_parameters.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("H_Min", "int", 0, "Hue Min", "", &HSVParamsConfig::H_Min)));
//#line 12 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __param_descriptions__.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("H_Min", "int", 0, "Hue Min", "", &HSVParamsConfig::H_Min)));
//#line 13 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __min__.S_Max = 0;
//#line 13 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __max__.S_Max = 255;
//#line 13 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __default__.S_Max = 255;
//#line 13 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      HSV_Params.abstract_parameters.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("S_Max", "int", 0, "Saturation Max", "", &HSVParamsConfig::S_Max)));
//#line 13 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __param_descriptions__.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("S_Max", "int", 0, "Saturation Max", "", &HSVParamsConfig::S_Max)));
//#line 14 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __min__.S_Min = 0;
//#line 14 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __max__.S_Min = 255;
//#line 14 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __default__.S_Min = 0;
//#line 14 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      HSV_Params.abstract_parameters.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("S_Min", "int", 0, "Saturation Min", "", &HSVParamsConfig::S_Min)));
//#line 14 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __param_descriptions__.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("S_Min", "int", 0, "Saturation Min", "", &HSVParamsConfig::S_Min)));
//#line 15 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __min__.V_Max = 0;
//#line 15 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __max__.V_Max = 255;
//#line 15 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __default__.V_Max = 255;
//#line 15 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      HSV_Params.abstract_parameters.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("V_Max", "int", 0, "Value Max", "", &HSVParamsConfig::V_Max)));
//#line 15 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __param_descriptions__.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("V_Max", "int", 0, "Value Max", "", &HSVParamsConfig::V_Max)));
//#line 16 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __min__.V_Min = 0;
//#line 16 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __max__.V_Min = 255;
//#line 16 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __default__.V_Min = 0;
//#line 16 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      HSV_Params.abstract_parameters.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("V_Min", "int", 0, "Value Min", "", &HSVParamsConfig::V_Min)));
//#line 16 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __param_descriptions__.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("V_Min", "int", 0, "Value Min", "", &HSVParamsConfig::V_Min)));
HSVParamsConfig::GroupDescription<HSVParamsConfig::DEFAULT::HSV_PARAMS::RED_HUE_EXTENSION, HSVParamsConfig::DEFAULT::HSV_PARAMS> red_Hue_Extension("red_Hue_Extension", "collapse", 1, 2, false, &HSVParamsConfig::DEFAULT::HSV_PARAMS::red_hue_extension);
//#line 18 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __min__.H_Extend = 0;
//#line 18 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __max__.H_Extend = 60;
//#line 18 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __default__.H_Extend = 0;
//#line 18 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      red_Hue_Extension.abstract_parameters.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("H_Extend", "int", 0, "The range of red Hue includes two areas: 0~60 and 300~360. Extending 0~60 can cover red more completely. After the extension, the default maximum value of Hue is 360.Enable only in red type.", "", &HSVParamsConfig::H_Extend)));
//#line 18 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      __param_descriptions__.push_back(HSVParamsConfig::AbstractParamDescriptionConstPtr(new HSVParamsConfig::ParamDescription<int>("H_Extend", "int", 0, "The range of red Hue includes two areas: 0~60 and 300~360. Extending 0~60 can cover red more completely. After the extension, the default maximum value of Hue is 360.Enable only in red type.", "", &HSVParamsConfig::H_Extend)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      red_Hue_Extension.convertParams();
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      HSV_Params.groups.push_back(HSVParamsConfig::AbstractGroupDescriptionConstPtr(new HSVParamsConfig::GroupDescription<HSVParamsConfig::DEFAULT::HSV_PARAMS::RED_HUE_EXTENSION, HSVParamsConfig::DEFAULT::HSV_PARAMS>(red_Hue_Extension)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(HSVParamsConfig::AbstractGroupDescriptionConstPtr(new HSVParamsConfig::GroupDescription<HSVParamsConfig::DEFAULT::HSV_PARAMS::RED_HUE_EXTENSION, HSVParamsConfig::DEFAULT::HSV_PARAMS>(red_Hue_Extension)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      HSV_Params.convertParams();
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(HSVParamsConfig::AbstractGroupDescriptionConstPtr(new HSVParamsConfig::GroupDescription<HSVParamsConfig::DEFAULT::HSV_PARAMS, HSVParamsConfig::DEFAULT>(HSV_Params)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(HSVParamsConfig::AbstractGroupDescriptionConstPtr(new HSVParamsConfig::GroupDescription<HSVParamsConfig::DEFAULT::HSV_PARAMS, HSVParamsConfig::DEFAULT>(HSV_Params)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(HSVParamsConfig::AbstractGroupDescriptionConstPtr(new HSVParamsConfig::GroupDescription<HSVParamsConfig::DEFAULT, HSVParamsConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<HSVParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<HSVParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<HSVParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    HSVParamsConfig __max__;
    HSVParamsConfig __min__;
    HSVParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const HSVParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static HSVParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &HSVParamsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const HSVParamsConfig &HSVParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const HSVParamsConfig &HSVParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const HSVParamsConfig &HSVParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<HSVParamsConfig::AbstractParamDescriptionConstPtr> &HSVParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<HSVParamsConfig::AbstractGroupDescriptionConstPtr> &HSVParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const HSVParamsConfigStatics *HSVParamsConfig::__get_statics__()
  {
    const static HSVParamsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = HSVParamsConfigStatics::get_instance();

    return statics;
  }

//#line 24 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      const int HSVParams_blue = 0;
//#line 25 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      const int HSVParams_green = 1;
//#line 26 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      const int HSVParams_red = 2;
//#line 27 "/home/ay/team2/src/sagittarius_arm_ros/sagittarius_perception/sagittarius_object_color_detector/config/HSVParams.cfg"
      const int HSVParams_customize = 3;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __HSVPARAMSRECONFIGURATOR_H__
