// Generated by gencpp from file sagittarius_object_color_detector/SGRCtrlAction.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_OBJECT_COLOR_DETECTOR_MESSAGE_SGRCTRLACTION_H
#define SAGITTARIUS_OBJECT_COLOR_DETECTOR_MESSAGE_SGRCTRLACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sagittarius_object_color_detector/SGRCtrlActionGoal.h>
#include <sagittarius_object_color_detector/SGRCtrlActionResult.h>
#include <sagittarius_object_color_detector/SGRCtrlActionFeedback.h>

namespace sagittarius_object_color_detector
{
template <class ContainerAllocator>
struct SGRCtrlAction_
{
  typedef SGRCtrlAction_<ContainerAllocator> Type;

  SGRCtrlAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  SGRCtrlAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sagittarius_object_color_detector::SGRCtrlActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::sagittarius_object_color_detector::SGRCtrlActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::sagittarius_object_color_detector::SGRCtrlActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> const> ConstPtr;

}; // struct SGRCtrlAction_

typedef ::sagittarius_object_color_detector::SGRCtrlAction_<std::allocator<void> > SGRCtrlAction;

typedef boost::shared_ptr< ::sagittarius_object_color_detector::SGRCtrlAction > SGRCtrlActionPtr;
typedef boost::shared_ptr< ::sagittarius_object_color_detector::SGRCtrlAction const> SGRCtrlActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator1> & lhs, const ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator1> & lhs, const ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sagittarius_object_color_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42bc8d97c3c0c3a6d93f0f493c18245a";
  }

  static const char* value(const ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42bc8d97c3c0c3a6ULL;
  static const uint64_t static_value2 = 0xd93f0f493c18245aULL;
};

template<class ContainerAllocator>
struct DataType< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sagittarius_object_color_detector/SGRCtrlAction";
  }

  static const char* value(const ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"SGRCtrlActionGoal action_goal\n"
"SGRCtrlActionResult action_result\n"
"SGRCtrlActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: sagittarius_object_color_detector/SGRCtrlActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"SGRCtrlGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sagittarius_object_color_detector/SGRCtrlGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"\n"
"# grasp_type 参数的定义项\n"
"# 设置当前夹爪状态，在动作执行之前设置\n"
"uint8 GRASP_NONE = 0 # 自定义动作下使用，夹爪不做处理\n"
"uint8 GRASP_OPEN = 1 # 打开夹爪, 放下动作\n"
"uint8 GRASP_CLOSE = 2 # 闭合夹爪, 抓取动作\n"
"\n"
"# action_type 参数的定义项\n"
"# 需要执行动作的类型，可以指定末端姿态或者自动计算\n"
"# 自定义姿态：是让机械臂到某个目标点\n"
"# 预设动作：是执行某个预设的一系列动作\n"
"uint8 ACTION_TYPE_XYZ = 0 # 自定义姿态：末端姿态使用动态计算\n"
"uint8 ACTION_TYPE_XYZ_RPY = 1 # 自定义姿态：末端姿态使用给定姿态\n"
"uint8 ACTION_TYPE_DEFINE_STAY = 2 # 预设动作：待机状态\n"
"uint8 ACTION_TYPE_DEFINE_SAVE = 3 # 预设动作：安全位置状态\n"
"uint8 ACTION_TYPE_PICK_XYZ = 4 # 预设动作：XYZ拾取动作\n"
"uint8 ACTION_TYPE_PICK_XYZ_RPY = 5 # 预设动作：XYZ+RPY拾取动作\n"
"uint8 ACTION_TYPE_PUT_XYZ = 6 # 预设动作：XYZ放下动作\n"
"uint8 ACTION_TYPE_PUT_XYZ_RPY = 7 # 预设动作：XYZ+RPY放下动作\n"
"\n"
"uint8 grasp_type  # 末端初始化状态\n"
"uint8 action_type  # 动作类型\n"
"\n"
"# 目标点位置\n"
"float64 pos_x\n"
"float64 pos_y\n"
"float64 pos_z\n"
"float64 pos_roll\n"
"float64 pos_pitch\n"
"float64 pos_yaw\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sagittarius_object_color_detector/SGRCtrlActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"SGRCtrlResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sagittarius_object_color_detector/SGRCtrlResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"uint8 SUCCESS = 0\n"
"uint8 ERROR = 1\n"
"uint8 PREEMPT = 2\n"
"uint8 PLAN_NOT_FOUND = 3\n"
"uint8 GRASP_FAILD = 4 # 抓空\n"
"\n"
"# 执行结果\n"
"uint8 result\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sagittarius_object_color_detector/SGRCtrlActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"SGRCtrlFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: sagittarius_object_color_detector/SGRCtrlFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"uint8 PLANNING = 0\n"
"uint8 EXEC_POSITION = 1\n"
"uint8 EXEC_GRASP = 2\n"
"\n"
"# 当前步骤\n"
"uint8 step\n"
;
  }

  static const char* value(const ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SGRCtrlAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sagittarius_object_color_detector::SGRCtrlAction_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action_goal: ";
    Printer< ::sagittarius_object_color_detector::SGRCtrlActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_result: ";
    Printer< ::sagittarius_object_color_detector::SGRCtrlActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_feedback: ";
    Printer< ::sagittarius_object_color_detector::SGRCtrlActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAGITTARIUS_OBJECT_COLOR_DETECTOR_MESSAGE_SGRCTRLACTION_H
