// Generated by gencpp from file sdk_sagittarius_arm/ArmInfoResponse.msg
// DO NOT EDIT!


#ifndef SDK_SAGITTARIUS_ARM_MESSAGE_ARMINFORESPONSE_H
#define SDK_SAGITTARIUS_ARM_MESSAGE_ARMINFORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdk_sagittarius_arm
{
template <class ContainerAllocator>
struct ArmInfoResponse_
{
  typedef ArmInfoResponse_<ContainerAllocator> Type;

  ArmInfoResponse_()
    : joint_names()
    , joint_ids()
    , lower_joint_limits()
    , upper_joint_limits()
    , velocity_limits()
    , lower_gripper_limit(0.0)
    , upper_gripper_limit(0.0)
    , use_gripper(false)
    , home_pos()
    , sleep_pos()
    , num_joints(0)
    , num_single_joints(0)  {
    }
  ArmInfoResponse_(const ContainerAllocator& _alloc)
    : joint_names(_alloc)
    , joint_ids(_alloc)
    , lower_joint_limits(_alloc)
    , upper_joint_limits(_alloc)
    , velocity_limits(_alloc)
    , lower_gripper_limit(0.0)
    , upper_gripper_limit(0.0)
    , use_gripper(false)
    , home_pos(_alloc)
    , sleep_pos(_alloc)
    , num_joints(0)
    , num_single_joints(0)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _joint_ids_type;
  _joint_ids_type joint_ids;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _lower_joint_limits_type;
  _lower_joint_limits_type lower_joint_limits;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _upper_joint_limits_type;
  _upper_joint_limits_type upper_joint_limits;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _velocity_limits_type;
  _velocity_limits_type velocity_limits;

   typedef double _lower_gripper_limit_type;
  _lower_gripper_limit_type lower_gripper_limit;

   typedef double _upper_gripper_limit_type;
  _upper_gripper_limit_type upper_gripper_limit;

   typedef uint8_t _use_gripper_type;
  _use_gripper_type use_gripper;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _home_pos_type;
  _home_pos_type home_pos;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _sleep_pos_type;
  _sleep_pos_type sleep_pos;

   typedef int8_t _num_joints_type;
  _num_joints_type num_joints;

   typedef int8_t _num_single_joints_type;
  _num_single_joints_type num_single_joints;





  typedef boost::shared_ptr< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ArmInfoResponse_

typedef ::sdk_sagittarius_arm::ArmInfoResponse_<std::allocator<void> > ArmInfoResponse;

typedef boost::shared_ptr< ::sdk_sagittarius_arm::ArmInfoResponse > ArmInfoResponsePtr;
typedef boost::shared_ptr< ::sdk_sagittarius_arm::ArmInfoResponse const> ArmInfoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator1> & lhs, const ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.joint_names == rhs.joint_names &&
    lhs.joint_ids == rhs.joint_ids &&
    lhs.lower_joint_limits == rhs.lower_joint_limits &&
    lhs.upper_joint_limits == rhs.upper_joint_limits &&
    lhs.velocity_limits == rhs.velocity_limits &&
    lhs.lower_gripper_limit == rhs.lower_gripper_limit &&
    lhs.upper_gripper_limit == rhs.upper_gripper_limit &&
    lhs.use_gripper == rhs.use_gripper &&
    lhs.home_pos == rhs.home_pos &&
    lhs.sleep_pos == rhs.sleep_pos &&
    lhs.num_joints == rhs.num_joints &&
    lhs.num_single_joints == rhs.num_single_joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator1> & lhs, const ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdk_sagittarius_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cbf67af7802be3e000262518104df12";
  }

  static const char* value(const ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cbf67af7802be3eULL;
  static const uint64_t static_value2 = 0x000262518104df12ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdk_sagittarius_arm/ArmInfoResponse";
  }

  static const char* value(const ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# joint names appear in the same order as they do in the joint_states.name vector\n"
"string[] joint_names\n"
"int16[] joint_ids\n"
"float64[] lower_joint_limits\n"
"float64[] upper_joint_limits\n"
"float64[] velocity_limits\n"
"float64 lower_gripper_limit\n"
"float64 upper_gripper_limit\n"
"bool use_gripper\n"
"float64[] home_pos\n"
"float64[] sleep_pos\n"
"int8 num_joints\n"
"int8 num_single_joints\n"
"\n"
;
  }

  static const char* value(const ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_names);
      stream.next(m.joint_ids);
      stream.next(m.lower_joint_limits);
      stream.next(m.upper_joint_limits);
      stream.next(m.velocity_limits);
      stream.next(m.lower_gripper_limit);
      stream.next(m.upper_gripper_limit);
      stream.next(m.use_gripper);
      stream.next(m.home_pos);
      stream.next(m.sleep_pos);
      stream.next(m.num_joints);
      stream.next(m.num_single_joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmInfoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdk_sagittarius_arm::ArmInfoResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint_names: ";
    if (v.joint_names.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.joint_names[i]);
    }
    if (v.joint_names.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_ids: ";
    if (v.joint_ids.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_ids.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int16_t>::stream(s, true ? std::string() : indent + "    ", v.joint_ids[i]);
    }
    if (v.joint_ids.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lower_joint_limits: ";
    if (v.lower_joint_limits.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lower_joint_limits.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.lower_joint_limits[i]);
    }
    if (v.lower_joint_limits.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "upper_joint_limits: ";
    if (v.upper_joint_limits.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.upper_joint_limits.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.upper_joint_limits[i]);
    }
    if (v.upper_joint_limits.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity_limits: ";
    if (v.velocity_limits.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.velocity_limits.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.velocity_limits[i]);
    }
    if (v.velocity_limits.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lower_gripper_limit: ";
    Printer<double>::stream(s, indent + "  ", v.lower_gripper_limit);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "upper_gripper_limit: ";
    Printer<double>::stream(s, indent + "  ", v.upper_gripper_limit);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "use_gripper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_gripper);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "home_pos: ";
    if (v.home_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.home_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.home_pos[i]);
    }
    if (v.home_pos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sleep_pos: ";
    if (v.sleep_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.sleep_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.sleep_pos[i]);
    }
    if (v.sleep_pos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num_joints: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num_joints);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num_single_joints: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num_single_joints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDK_SAGITTARIUS_ARM_MESSAGE_ARMINFORESPONSE_H
