// Generated by gencpp from file sdk_sagittarius_arm/ArmInfo.msg
// DO NOT EDIT!


#ifndef SDK_SAGITTARIUS_ARM_MESSAGE_ARMINFO_H
#define SDK_SAGITTARIUS_ARM_MESSAGE_ARMINFO_H

#include <ros/service_traits.h>


#include <sdk_sagittarius_arm/ArmInfoRequest.h>
#include <sdk_sagittarius_arm/ArmInfoResponse.h>


namespace sdk_sagittarius_arm
{

struct ArmInfo
{

typedef ArmInfoRequest Request;
typedef ArmInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmInfo
} // namespace sdk_sagittarius_arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sdk_sagittarius_arm::ArmInfo > {
  static const char* value()
  {
    return "8cbf67af7802be3e000262518104df12";
  }

  static const char* value(const ::sdk_sagittarius_arm::ArmInfo&) { return value(); }
};

template<>
struct DataType< ::sdk_sagittarius_arm::ArmInfo > {
  static const char* value()
  {
    return "sdk_sagittarius_arm/ArmInfo";
  }

  static const char* value(const ::sdk_sagittarius_arm::ArmInfo&) { return value(); }
};


// service_traits::MD5Sum< ::sdk_sagittarius_arm::ArmInfoRequest> should match
// service_traits::MD5Sum< ::sdk_sagittarius_arm::ArmInfo >
template<>
struct MD5Sum< ::sdk_sagittarius_arm::ArmInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sdk_sagittarius_arm::ArmInfo >::value();
  }
  static const char* value(const ::sdk_sagittarius_arm::ArmInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdk_sagittarius_arm::ArmInfoRequest> should match
// service_traits::DataType< ::sdk_sagittarius_arm::ArmInfo >
template<>
struct DataType< ::sdk_sagittarius_arm::ArmInfoRequest>
{
  static const char* value()
  {
    return DataType< ::sdk_sagittarius_arm::ArmInfo >::value();
  }
  static const char* value(const ::sdk_sagittarius_arm::ArmInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sdk_sagittarius_arm::ArmInfoResponse> should match
// service_traits::MD5Sum< ::sdk_sagittarius_arm::ArmInfo >
template<>
struct MD5Sum< ::sdk_sagittarius_arm::ArmInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sdk_sagittarius_arm::ArmInfo >::value();
  }
  static const char* value(const ::sdk_sagittarius_arm::ArmInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdk_sagittarius_arm::ArmInfoResponse> should match
// service_traits::DataType< ::sdk_sagittarius_arm::ArmInfo >
template<>
struct DataType< ::sdk_sagittarius_arm::ArmInfoResponse>
{
  static const char* value()
  {
    return DataType< ::sdk_sagittarius_arm::ArmInfo >::value();
  }
  static const char* value(const ::sdk_sagittarius_arm::ArmInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SDK_SAGITTARIUS_ARM_MESSAGE_ARMINFO_H
