// Generated by gencpp from file sdk_sagittarius_arm/ServoRtInfo.msg
// DO NOT EDIT!


#ifndef SDK_SAGITTARIUS_ARM_MESSAGE_SERVORTINFO_H
#define SDK_SAGITTARIUS_ARM_MESSAGE_SERVORTINFO_H

#include <ros/service_traits.h>


#include <sdk_sagittarius_arm/ServoRtInfoRequest.h>
#include <sdk_sagittarius_arm/ServoRtInfoResponse.h>


namespace sdk_sagittarius_arm
{

struct ServoRtInfo
{

typedef ServoRtInfoRequest Request;
typedef ServoRtInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoRtInfo
} // namespace sdk_sagittarius_arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sdk_sagittarius_arm::ServoRtInfo > {
  static const char* value()
  {
    return "d3106e0c44e7c7adcad01214d53da198";
  }

  static const char* value(const ::sdk_sagittarius_arm::ServoRtInfo&) { return value(); }
};

template<>
struct DataType< ::sdk_sagittarius_arm::ServoRtInfo > {
  static const char* value()
  {
    return "sdk_sagittarius_arm/ServoRtInfo";
  }

  static const char* value(const ::sdk_sagittarius_arm::ServoRtInfo&) { return value(); }
};


// service_traits::MD5Sum< ::sdk_sagittarius_arm::ServoRtInfoRequest> should match
// service_traits::MD5Sum< ::sdk_sagittarius_arm::ServoRtInfo >
template<>
struct MD5Sum< ::sdk_sagittarius_arm::ServoRtInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sdk_sagittarius_arm::ServoRtInfo >::value();
  }
  static const char* value(const ::sdk_sagittarius_arm::ServoRtInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdk_sagittarius_arm::ServoRtInfoRequest> should match
// service_traits::DataType< ::sdk_sagittarius_arm::ServoRtInfo >
template<>
struct DataType< ::sdk_sagittarius_arm::ServoRtInfoRequest>
{
  static const char* value()
  {
    return DataType< ::sdk_sagittarius_arm::ServoRtInfo >::value();
  }
  static const char* value(const ::sdk_sagittarius_arm::ServoRtInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sdk_sagittarius_arm::ServoRtInfoResponse> should match
// service_traits::MD5Sum< ::sdk_sagittarius_arm::ServoRtInfo >
template<>
struct MD5Sum< ::sdk_sagittarius_arm::ServoRtInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sdk_sagittarius_arm::ServoRtInfo >::value();
  }
  static const char* value(const ::sdk_sagittarius_arm::ServoRtInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdk_sagittarius_arm::ServoRtInfoResponse> should match
// service_traits::DataType< ::sdk_sagittarius_arm::ServoRtInfo >
template<>
struct DataType< ::sdk_sagittarius_arm::ServoRtInfoResponse>
{
  static const char* value()
  {
    return DataType< ::sdk_sagittarius_arm::ServoRtInfo >::value();
  }
  static const char* value(const ::sdk_sagittarius_arm::ServoRtInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SDK_SAGITTARIUS_ARM_MESSAGE_SERVORTINFO_H
