// Auto-generated. Do not edit!

// (in-package sagittarius_object_color_detector.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let SGRCtrlGoal = require('./SGRCtrlGoal.js');
let std_msgs = _finder('std_msgs');
let actionlib_msgs = _finder('actionlib_msgs');

//-----------------------------------------------------------

class SGRCtrlActionGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.header = null;
      this.goal_id = null;
      this.goal = null;
    }
    else {
      if (initObj.hasOwnProperty('header')) {
        this.header = initObj.header
      }
      else {
        this.header = new std_msgs.msg.Header();
      }
      if (initObj.hasOwnProperty('goal_id')) {
        this.goal_id = initObj.goal_id
      }
      else {
        this.goal_id = new actionlib_msgs.msg.GoalID();
      }
      if (initObj.hasOwnProperty('goal')) {
        this.goal = initObj.goal
      }
      else {
        this.goal = new SGRCtrlGoal();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SGRCtrlActionGoal
    // Serialize message field [header]
    bufferOffset = std_msgs.msg.Header.serialize(obj.header, buffer, bufferOffset);
    // Serialize message field [goal_id]
    bufferOffset = actionlib_msgs.msg.GoalID.serialize(obj.goal_id, buffer, bufferOffset);
    // Serialize message field [goal]
    bufferOffset = SGRCtrlGoal.serialize(obj.goal, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SGRCtrlActionGoal
    let len;
    let data = new SGRCtrlActionGoal(null);
    // Deserialize message field [header]
    data.header = std_msgs.msg.Header.deserialize(buffer, bufferOffset);
    // Deserialize message field [goal_id]
    data.goal_id = actionlib_msgs.msg.GoalID.deserialize(buffer, bufferOffset);
    // Deserialize message field [goal]
    data.goal = SGRCtrlGoal.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.Header.getMessageSize(object.header);
    length += actionlib_msgs.msg.GoalID.getMessageSize(object.goal_id);
    return length + 50;
  }

  static datatype() {
    // Returns string type for a message object
    return 'sagittarius_object_color_detector/SGRCtrlActionGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '88690564d9e0e03f5ffd356cf575c626';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    SGRCtrlGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: sagittarius_object_color_detector/SGRCtrlGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    
    # grasp_type 参数的定义项
    # 设置当前夹爪状态，在动作执行之前设置
    uint8 GRASP_NONE = 0 # 自定义动作下使用，夹爪不做处理
    uint8 GRASP_OPEN = 1 # 打开夹爪, 放下动作
    uint8 GRASP_CLOSE = 2 # 闭合夹爪, 抓取动作
    
    # action_type 参数的定义项
    # 需要执行动作的类型，可以指定末端姿态或者自动计算
    # 自定义姿态：是让机械臂到某个目标点
    # 预设动作：是执行某个预设的一系列动作
    uint8 ACTION_TYPE_XYZ = 0 # 自定义姿态：末端姿态使用动态计算
    uint8 ACTION_TYPE_XYZ_RPY = 1 # 自定义姿态：末端姿态使用给定姿态
    uint8 ACTION_TYPE_DEFINE_STAY = 2 # 预设动作：待机状态
    uint8 ACTION_TYPE_DEFINE_SAVE = 3 # 预设动作：安全位置状态
    uint8 ACTION_TYPE_PICK_XYZ = 4 # 预设动作：XYZ拾取动作
    uint8 ACTION_TYPE_PICK_XYZ_RPY = 5 # 预设动作：XYZ+RPY拾取动作
    uint8 ACTION_TYPE_PUT_XYZ = 6 # 预设动作：XYZ放下动作
    uint8 ACTION_TYPE_PUT_XYZ_RPY = 7 # 预设动作：XYZ+RPY放下动作
    
    uint8 grasp_type  # 末端初始化状态
    uint8 action_type  # 动作类型
    
    # 目标点位置
    float64 pos_x
    float64 pos_y
    float64 pos_z
    float64 pos_roll
    float64 pos_pitch
    float64 pos_yaw
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SGRCtrlActionGoal(null);
    if (msg.header !== undefined) {
      resolved.header = std_msgs.msg.Header.Resolve(msg.header)
    }
    else {
      resolved.header = new std_msgs.msg.Header()
    }

    if (msg.goal_id !== undefined) {
      resolved.goal_id = actionlib_msgs.msg.GoalID.Resolve(msg.goal_id)
    }
    else {
      resolved.goal_id = new actionlib_msgs.msg.GoalID()
    }

    if (msg.goal !== undefined) {
      resolved.goal = SGRCtrlGoal.Resolve(msg.goal)
    }
    else {
      resolved.goal = new SGRCtrlGoal()
    }

    return resolved;
    }
};

module.exports = SGRCtrlActionGoal;
