// Auto-generated. Do not edit!

// (in-package sagittarius_object_color_detector.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let SGRCtrlActionGoal = require('./SGRCtrlActionGoal.js');
let SGRCtrlActionResult = require('./SGRCtrlActionResult.js');
let SGRCtrlActionFeedback = require('./SGRCtrlActionFeedback.js');

//-----------------------------------------------------------

class SGRCtrlAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new SGRCtrlActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new SGRCtrlActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new SGRCtrlActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SGRCtrlAction
    // Serialize message field [action_goal]
    bufferOffset = SGRCtrlActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = SGRCtrlActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = SGRCtrlActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SGRCtrlAction
    let len;
    let data = new SGRCtrlAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = SGRCtrlActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = SGRCtrlActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = SGRCtrlActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += SGRCtrlActionGoal.getMessageSize(object.action_goal);
    length += SGRCtrlActionResult.getMessageSize(object.action_result);
    length += SGRCtrlActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'sagittarius_object_color_detector/SGRCtrlAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '42bc8d97c3c0c3a6d93f0f493c18245a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    SGRCtrlActionGoal action_goal
    SGRCtrlActionResult action_result
    SGRCtrlActionFeedback action_feedback
    
    ================================================================================
    MSG: sagittarius_object_color_detector/SGRCtrlActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    SGRCtrlGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: sagittarius_object_color_detector/SGRCtrlGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    
    # grasp_type 参数的定义项
    # 设置当前夹爪状态，在动作执行之前设置
    uint8 GRASP_NONE = 0 # 自定义动作下使用，夹爪不做处理
    uint8 GRASP_OPEN = 1 # 打开夹爪, 放下动作
    uint8 GRASP_CLOSE = 2 # 闭合夹爪, 抓取动作
    
    # action_type 参数的定义项
    # 需要执行动作的类型，可以指定末端姿态或者自动计算
    # 自定义姿态：是让机械臂到某个目标点
    # 预设动作：是执行某个预设的一系列动作
    uint8 ACTION_TYPE_XYZ = 0 # 自定义姿态：末端姿态使用动态计算
    uint8 ACTION_TYPE_XYZ_RPY = 1 # 自定义姿态：末端姿态使用给定姿态
    uint8 ACTION_TYPE_DEFINE_STAY = 2 # 预设动作：待机状态
    uint8 ACTION_TYPE_DEFINE_SAVE = 3 # 预设动作：安全位置状态
    uint8 ACTION_TYPE_PICK_XYZ = 4 # 预设动作：XYZ拾取动作
    uint8 ACTION_TYPE_PICK_XYZ_RPY = 5 # 预设动作：XYZ+RPY拾取动作
    uint8 ACTION_TYPE_PUT_XYZ = 6 # 预设动作：XYZ放下动作
    uint8 ACTION_TYPE_PUT_XYZ_RPY = 7 # 预设动作：XYZ+RPY放下动作
    
    uint8 grasp_type  # 末端初始化状态
    uint8 action_type  # 动作类型
    
    # 目标点位置
    float64 pos_x
    float64 pos_y
    float64 pos_z
    float64 pos_roll
    float64 pos_pitch
    float64 pos_yaw
    
    
    ================================================================================
    MSG: sagittarius_object_color_detector/SGRCtrlActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    SGRCtrlResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: sagittarius_object_color_detector/SGRCtrlResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    uint8 SUCCESS = 0
    uint8 ERROR = 1
    uint8 PREEMPT = 2
    uint8 PLAN_NOT_FOUND = 3
    uint8 GRASP_FAILD = 4 # 抓空
    
    # 执行结果
    uint8 result
    
    
    ================================================================================
    MSG: sagittarius_object_color_detector/SGRCtrlActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    SGRCtrlFeedback feedback
    
    ================================================================================
    MSG: sagittarius_object_color_detector/SGRCtrlFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    uint8 PLANNING = 0
    uint8 EXEC_POSITION = 1
    uint8 EXEC_GRASP = 2
    
    # 当前步骤
    uint8 step
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SGRCtrlAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = SGRCtrlActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new SGRCtrlActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = SGRCtrlActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new SGRCtrlActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = SGRCtrlActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new SGRCtrlActionFeedback()
    }

    return resolved;
    }
};

module.exports = SGRCtrlAction;
