// Auto-generated. Do not edit!

// (in-package sagittarius_object_color_detector.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SGRCtrlFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.step = null;
    }
    else {
      if (initObj.hasOwnProperty('step')) {
        this.step = initObj.step
      }
      else {
        this.step = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SGRCtrlFeedback
    // Serialize message field [step]
    bufferOffset = _serializer.uint8(obj.step, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SGRCtrlFeedback
    let len;
    let data = new SGRCtrlFeedback(null);
    // Deserialize message field [step]
    data.step = _deserializer.uint8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'sagittarius_object_color_detector/SGRCtrlFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '16415215c939077a0b815877705c9bee';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    uint8 PLANNING = 0
    uint8 EXEC_POSITION = 1
    uint8 EXEC_GRASP = 2
    
    # 当前步骤
    uint8 step
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SGRCtrlFeedback(null);
    if (msg.step !== undefined) {
      resolved.step = msg.step;
    }
    else {
      resolved.step = 0
    }

    return resolved;
    }
};

// Constants for message
SGRCtrlFeedback.Constants = {
  PLANNING: 0,
  EXEC_POSITION: 1,
  EXEC_GRASP: 2,
}

module.exports = SGRCtrlFeedback;
