# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sagittarius_joy/arm_joy.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class arm_joy(genpy.Message):
  _md5sum = "aee021bfef1da6cac98533007e49228c"
  _type = "sagittarius_joy/arm_joy"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
# This message is used specifically in the sagittarius_joy package
#
# Maps raw 'joy' commands to more specific ones to control an sagittarius

# enum values that define the joystick controls for the robot

#########################################################################################################

# Control the motion of the virtual 'ee_gripper_link' or end effector using the modern_robotics_ik engine
# Position Control
int8 EE_X_INC = 1
int8 EE_X_DEC = 2
int8 EE_Y_INC = 3
int8 EE_Y_DEC = 4
int8 EE_Z_INC = 5
int8 EE_Z_DEC = 6

# Orientation Control
int8 EE_ROLL_CCW = 7
int8 EE_ROLL_CW = 8
int8 EE_PITCH_UP = 9
int8 EE_PITCH_DOWN = 10
int8 EE_YAW_LEFT = 11
int8 EE_YAW_RIGHT = 12

#########################################################################################################

# Control the motion of independent joints on the Arm or send predefined robot poses
# Pose Control
int8 UP_POSE = 13
int8 HOME_POSE = 14
int8 SLEEP_POSE = 15

# Position and Orientation reset
int8 POSITION_RESET = 16
int8 ORIENTATION_RESET = 17

#########################################################################################################

# Customize configurations for the Sagittarius Arm
# Inc/Dec Joint speed
int8 SPEED_INC = 18
int8 SPEED_DEC = 19

# Inc/Dec Gripper spacing
int8 GRIPPER_SPACING_INC = 20
int8 GRIPPER_SPACING_DEC = 21

# Torque On/Off all servos
int8 TORQUE_ON = 22
int8 TORQUE_OFF = 23

# Torque Inc/Dec all servos
int8 TORQUE_INC = 24
int8 TORQUE_DEC = 25

#########################################################################################################

# Other function for the Sagittarius Arm
# Super Key
int8 SUPER_KEY = 26

#########################################################################################################

# Control the motion of the Sagittarius Arm
int8 ee_x_cmd
int8 ee_y_cmd
int8 ee_z_cmd
int8 ee_roll_cmd
int8 ee_pitch_cmd
int8 ee_yaw_cmd

# Independent Joint/Pose Control
int8 pose_cmd
int8 reset_cmd

# Misc. Configs
int8 speed_cmd
int8 gripper_spacing_cmd
int8 torque_cmd
int8 torque_lev_cmd

# Super key
int8 super_cmd
"""
  # Pseudo-constants
  EE_X_INC = 1
  EE_X_DEC = 2
  EE_Y_INC = 3
  EE_Y_DEC = 4
  EE_Z_INC = 5
  EE_Z_DEC = 6
  EE_ROLL_CCW = 7
  EE_ROLL_CW = 8
  EE_PITCH_UP = 9
  EE_PITCH_DOWN = 10
  EE_YAW_LEFT = 11
  EE_YAW_RIGHT = 12
  UP_POSE = 13
  HOME_POSE = 14
  SLEEP_POSE = 15
  POSITION_RESET = 16
  ORIENTATION_RESET = 17
  SPEED_INC = 18
  SPEED_DEC = 19
  GRIPPER_SPACING_INC = 20
  GRIPPER_SPACING_DEC = 21
  TORQUE_ON = 22
  TORQUE_OFF = 23
  TORQUE_INC = 24
  TORQUE_DEC = 25
  SUPER_KEY = 26

  __slots__ = ['ee_x_cmd','ee_y_cmd','ee_z_cmd','ee_roll_cmd','ee_pitch_cmd','ee_yaw_cmd','pose_cmd','reset_cmd','speed_cmd','gripper_spacing_cmd','torque_cmd','torque_lev_cmd','super_cmd']
  _slot_types = ['int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ee_x_cmd,ee_y_cmd,ee_z_cmd,ee_roll_cmd,ee_pitch_cmd,ee_yaw_cmd,pose_cmd,reset_cmd,speed_cmd,gripper_spacing_cmd,torque_cmd,torque_lev_cmd,super_cmd

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(arm_joy, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ee_x_cmd is None:
        self.ee_x_cmd = 0
      if self.ee_y_cmd is None:
        self.ee_y_cmd = 0
      if self.ee_z_cmd is None:
        self.ee_z_cmd = 0
      if self.ee_roll_cmd is None:
        self.ee_roll_cmd = 0
      if self.ee_pitch_cmd is None:
        self.ee_pitch_cmd = 0
      if self.ee_yaw_cmd is None:
        self.ee_yaw_cmd = 0
      if self.pose_cmd is None:
        self.pose_cmd = 0
      if self.reset_cmd is None:
        self.reset_cmd = 0
      if self.speed_cmd is None:
        self.speed_cmd = 0
      if self.gripper_spacing_cmd is None:
        self.gripper_spacing_cmd = 0
      if self.torque_cmd is None:
        self.torque_cmd = 0
      if self.torque_lev_cmd is None:
        self.torque_lev_cmd = 0
      if self.super_cmd is None:
        self.super_cmd = 0
    else:
      self.ee_x_cmd = 0
      self.ee_y_cmd = 0
      self.ee_z_cmd = 0
      self.ee_roll_cmd = 0
      self.ee_pitch_cmd = 0
      self.ee_yaw_cmd = 0
      self.pose_cmd = 0
      self.reset_cmd = 0
      self.speed_cmd = 0
      self.gripper_spacing_cmd = 0
      self.torque_cmd = 0
      self.torque_lev_cmd = 0
      self.super_cmd = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_13b().pack(_x.ee_x_cmd, _x.ee_y_cmd, _x.ee_z_cmd, _x.ee_roll_cmd, _x.ee_pitch_cmd, _x.ee_yaw_cmd, _x.pose_cmd, _x.reset_cmd, _x.speed_cmd, _x.gripper_spacing_cmd, _x.torque_cmd, _x.torque_lev_cmd, _x.super_cmd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.ee_x_cmd, _x.ee_y_cmd, _x.ee_z_cmd, _x.ee_roll_cmd, _x.ee_pitch_cmd, _x.ee_yaw_cmd, _x.pose_cmd, _x.reset_cmd, _x.speed_cmd, _x.gripper_spacing_cmd, _x.torque_cmd, _x.torque_lev_cmd, _x.super_cmd,) = _get_struct_13b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_13b().pack(_x.ee_x_cmd, _x.ee_y_cmd, _x.ee_z_cmd, _x.ee_roll_cmd, _x.ee_pitch_cmd, _x.ee_yaw_cmd, _x.pose_cmd, _x.reset_cmd, _x.speed_cmd, _x.gripper_spacing_cmd, _x.torque_cmd, _x.torque_lev_cmd, _x.super_cmd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.ee_x_cmd, _x.ee_y_cmd, _x.ee_z_cmd, _x.ee_roll_cmd, _x.ee_pitch_cmd, _x.ee_yaw_cmd, _x.pose_cmd, _x.reset_cmd, _x.speed_cmd, _x.gripper_spacing_cmd, _x.torque_cmd, _x.torque_lev_cmd, _x.super_cmd,) = _get_struct_13b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13b = None
def _get_struct_13b():
    global _struct_13b
    if _struct_13b is None:
        _struct_13b = struct.Struct("<13b")
    return _struct_13b
