// Generated by gencpp from file sagittarius_openclaw_bridge/RunCommandResponse.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMANDRESPONSE_H
#define SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sagittarius_openclaw_bridge
{
template <class ContainerAllocator>
struct RunCommandResponse_
{
  typedef RunCommandResponse_<ContainerAllocator> Type;

  RunCommandResponse_()
    : success(false)
    , result_code(0)
    , message()
    , detected_color()
    , target_x(0.0)
    , target_y(0.0)
    , target_z(0.0)  {
    }
  RunCommandResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , result_code(0)
    , message(_alloc)
    , detected_color(_alloc)
    , target_x(0.0)
    , target_y(0.0)
    , target_z(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef int32_t _result_code_type;
  _result_code_type result_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _detected_color_type;
  _detected_color_type detected_color;

   typedef double _target_x_type;
  _target_x_type target_x;

   typedef double _target_y_type;
  _target_y_type target_y;

   typedef double _target_z_type;
  _target_z_type target_z;





  typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RunCommandResponse_

typedef ::sagittarius_openclaw_bridge::RunCommandResponse_<std::allocator<void> > RunCommandResponse;

typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandResponse > RunCommandResponsePtr;
typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandResponse const> RunCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator1> & lhs, const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.result_code == rhs.result_code &&
    lhs.message == rhs.message &&
    lhs.detected_color == rhs.detected_color &&
    lhs.target_x == rhs.target_x &&
    lhs.target_y == rhs.target_y &&
    lhs.target_z == rhs.target_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator1> & lhs, const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sagittarius_openclaw_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cb39e6c96588ccbabca928ecc0edafb";
  }

  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cb39e6c96588ccbULL;
  static const uint64_t static_value2 = 0xabca928ecc0edafbULL;
};

template<class ContainerAllocator>
struct DataType< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sagittarius_openclaw_bridge/RunCommandResponse";
  }

  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"int32 result_code\n"
"string message\n"
"string detected_color\n"
"float64 target_x\n"
"float64 target_y\n"
"float64 target_z\n"
"\n"
;
  }

  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.result_code);
      stream.next(m.message);
      stream.next(m.detected_color);
      stream.next(m.target_x);
      stream.next(m.target_y);
      stream.next(m.target_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result_code);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detected_color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.detected_color);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_x: ";
    Printer<double>::stream(s, indent + "  ", v.target_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_y: ";
    Printer<double>::stream(s, indent + "  ", v.target_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_z: ";
    Printer<double>::stream(s, indent + "  ", v.target_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMANDRESPONSE_H
