// Generated by gencpp from file sagittarius_openclaw_bridge/RunCommand.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMAND_H
#define SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMAND_H

#include <ros/service_traits.h>


#include <sagittarius_openclaw_bridge/RunCommandRequest.h>
#include <sagittarius_openclaw_bridge/RunCommandResponse.h>


namespace sagittarius_openclaw_bridge
{

struct RunCommand
{

typedef RunCommandRequest Request;
typedef RunCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RunCommand
} // namespace sagittarius_openclaw_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sagittarius_openclaw_bridge::RunCommand > {
  static const char* value()
  {
    return "1b28e903356241bb6dd2177521686ce9";
  }

  static const char* value(const ::sagittarius_openclaw_bridge::RunCommand&) { return value(); }
};

template<>
struct DataType< ::sagittarius_openclaw_bridge::RunCommand > {
  static const char* value()
  {
    return "sagittarius_openclaw_bridge/RunCommand";
  }

  static const char* value(const ::sagittarius_openclaw_bridge::RunCommand&) { return value(); }
};


// service_traits::MD5Sum< ::sagittarius_openclaw_bridge::RunCommandRequest> should match
// service_traits::MD5Sum< ::sagittarius_openclaw_bridge::RunCommand >
template<>
struct MD5Sum< ::sagittarius_openclaw_bridge::RunCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sagittarius_openclaw_bridge::RunCommand >::value();
  }
  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sagittarius_openclaw_bridge::RunCommandRequest> should match
// service_traits::DataType< ::sagittarius_openclaw_bridge::RunCommand >
template<>
struct DataType< ::sagittarius_openclaw_bridge::RunCommandRequest>
{
  static const char* value()
  {
    return DataType< ::sagittarius_openclaw_bridge::RunCommand >::value();
  }
  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sagittarius_openclaw_bridge::RunCommandResponse> should match
// service_traits::MD5Sum< ::sagittarius_openclaw_bridge::RunCommand >
template<>
struct MD5Sum< ::sagittarius_openclaw_bridge::RunCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sagittarius_openclaw_bridge::RunCommand >::value();
  }
  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sagittarius_openclaw_bridge::RunCommandResponse> should match
// service_traits::DataType< ::sagittarius_openclaw_bridge::RunCommand >
template<>
struct DataType< ::sagittarius_openclaw_bridge::RunCommandResponse>
{
  static const char* value()
  {
    return DataType< ::sagittarius_openclaw_bridge::RunCommand >::value();
  }
  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMAND_H
