// Generated by gencpp from file sagittarius_openclaw_bridge/RunCommandResponse.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMANDRESPONSE_H
#define SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sagittarius_openclaw_bridge
{
template <class ContainerAllocator>
struct RunCommandResponse_
{
  typedef RunCommandResponse_<ContainerAllocator> Type;

  RunCommandResponse_()
    : success(false)
    , result_code(0)
    , message()
    , detected_color()
    , target_x(0.0)
    , target_y(0.0)
    , target_z(0.0)
    , detected_count(0)
    , detected_colors()
    , target_xs()
    , target_ys()
    , target_zs()  {
    }
  RunCommandResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , result_code(0)
    , message(_alloc)
    , detected_color(_alloc)
    , target_x(0.0)
    , target_y(0.0)
    , target_z(0.0)
    , detected_count(0)
    , detected_colors(_alloc)
    , target_xs(_alloc)
    , target_ys(_alloc)
    , target_zs(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef int32_t _result_code_type;
  _result_code_type result_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _detected_color_type;
  _detected_color_type detected_color;

   typedef double _target_x_type;
  _target_x_type target_x;

   typedef double _target_y_type;
  _target_y_type target_y;

   typedef double _target_z_type;
  _target_z_type target_z;

   typedef int32_t _detected_count_type;
  _detected_count_type detected_count;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _detected_colors_type;
  _detected_colors_type detected_colors;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _target_xs_type;
  _target_xs_type target_xs;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _target_ys_type;
  _target_ys_type target_ys;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _target_zs_type;
  _target_zs_type target_zs;





  typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RunCommandResponse_

typedef ::sagittarius_openclaw_bridge::RunCommandResponse_<std::allocator<void> > RunCommandResponse;

typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandResponse > RunCommandResponsePtr;
typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandResponse const> RunCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator1> & lhs, const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.result_code == rhs.result_code &&
    lhs.message == rhs.message &&
    lhs.detected_color == rhs.detected_color &&
    lhs.target_x == rhs.target_x &&
    lhs.target_y == rhs.target_y &&
    lhs.target_z == rhs.target_z &&
    lhs.detected_count == rhs.detected_count &&
    lhs.detected_colors == rhs.detected_colors &&
    lhs.target_xs == rhs.target_xs &&
    lhs.target_ys == rhs.target_ys &&
    lhs.target_zs == rhs.target_zs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator1> & lhs, const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sagittarius_openclaw_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "845e95e1ecaca59e1250bd15e5128521";
  }

  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x845e95e1ecaca59eULL;
  static const uint64_t static_value2 = 0x1250bd15e5128521ULL;
};

template<class ContainerAllocator>
struct DataType< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sagittarius_openclaw_bridge/RunCommandResponse";
  }

  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"int32 result_code\n"
"string message\n"
"string detected_color\n"
"float64 target_x\n"
"float64 target_y\n"
"float64 target_z\n"
"int32 detected_count\n"
"string[] detected_colors\n"
"float64[] target_xs\n"
"float64[] target_ys\n"
"float64[] target_zs\n"
"\n"
;
  }

  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.result_code);
      stream.next(m.message);
      stream.next(m.detected_color);
      stream.next(m.target_x);
      stream.next(m.target_y);
      stream.next(m.target_z);
      stream.next(m.detected_count);
      stream.next(m.detected_colors);
      stream.next(m.target_xs);
      stream.next(m.target_ys);
      stream.next(m.target_zs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sagittarius_openclaw_bridge::RunCommandResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result_code);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detected_color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.detected_color);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_x: ";
    Printer<double>::stream(s, indent + "  ", v.target_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_y: ";
    Printer<double>::stream(s, indent + "  ", v.target_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_z: ";
    Printer<double>::stream(s, indent + "  ", v.target_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detected_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.detected_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detected_colors: ";
    if (v.detected_colors.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.detected_colors.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.detected_colors[i]);
    }
    if (v.detected_colors.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_xs: ";
    if (v.target_xs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.target_xs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.target_xs[i]);
    }
    if (v.target_xs.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_ys: ";
    if (v.target_ys.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.target_ys.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.target_ys[i]);
    }
    if (v.target_ys.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_zs: ";
    if (v.target_zs.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.target_zs.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.target_zs[i]);
    }
    if (v.target_zs.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMANDRESPONSE_H
