// Generated by gencpp from file sagittarius_openclaw_bridge/RunCommandRequest.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMANDREQUEST_H
#define SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sagittarius_openclaw_bridge
{
template <class ContainerAllocator>
struct RunCommandRequest_
{
  typedef RunCommandRequest_<ContainerAllocator> Type;

  RunCommandRequest_()
    : command()
    , color()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , use_rpy(false)  {
    }
  RunCommandRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , color(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , use_rpy(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef uint8_t _use_rpy_type;
  _use_rpy_type use_rpy;





  typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RunCommandRequest_

typedef ::sagittarius_openclaw_bridge::RunCommandRequest_<std::allocator<void> > RunCommandRequest;

typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandRequest > RunCommandRequestPtr;
typedef boost::shared_ptr< ::sagittarius_openclaw_bridge::RunCommandRequest const> RunCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator1> & lhs, const ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.color == rhs.color &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.use_rpy == rhs.use_rpy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator1> & lhs, const ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sagittarius_openclaw_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e3b1e61190ff0255a38079e19663885";
  }

  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e3b1e61190ff025ULL;
  static const uint64_t static_value2 = 0x5a38079e19663885ULL;
};

template<class ContainerAllocator>
struct DataType< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sagittarius_openclaw_bridge/RunCommandRequest";
  }

  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
"string color\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"bool use_rpy\n"
;
  }

  static const char* value(const ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.color);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.use_rpy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sagittarius_openclaw_bridge::RunCommandRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "use_rpy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_rpy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAGITTARIUS_OPENCLAW_BRIDGE_MESSAGE_RUNCOMMANDREQUEST_H
