(cl:defpackage sagittarius_object_color_detector-msg
  (:use )
  (:export
   "<SGRCTRLACTION>"
   "SGRCTRLACTION"
   "<SGRCTRLACTIONFEEDBACK>"
   "SGRCTRLACTIONFEEDBACK"
   "<SGRCTRLACTIONGOAL>"
   "SGRCTRLACTIONGOAL"
   "<SGRCTRLACTIONRESULT>"
   "SGRCTRLACTIONRESULT"
   "<SGRCTRLFEEDBACK>"
   "SGRCTRLFEEDBACK"
   "<SGRCTRLGOAL>"
   "SGRCTRLGOAL"
   "<SGRCTRLRESULT>"
   "SGRCTRLRESULT"
  ))

