; Auto-generated. Do not edit!


(cl:in-package sagittarius_object_color_detector-msg)


;//! \htmlinclude SGRCtrlResult.msg.html

(cl:defclass <SGRCtrlResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:fixnum
    :initform 0))
)

(cl:defclass SGRCtrlResult (<SGRCtrlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SGRCtrlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SGRCtrlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sagittarius_object_color_detector-msg:<SGRCtrlResult> is deprecated: use sagittarius_object_color_detector-msg:SGRCtrlResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <SGRCtrlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sagittarius_object_color_detector-msg:result-val is deprecated.  Use sagittarius_object_color_detector-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<SGRCtrlResult>)))
    "Constants for message type '<SGRCtrlResult>"
  '((:SUCCESS . 0)
    (:ERROR . 1)
    (:PREEMPT . 2)
    (:PLAN_NOT_FOUND . 3)
    (:GRASP_FAILD . 4))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'SGRCtrlResult)))
    "Constants for message type 'SGRCtrlResult"
  '((:SUCCESS . 0)
    (:ERROR . 1)
    (:PREEMPT . 2)
    (:PLAN_NOT_FOUND . 3)
    (:GRASP_FAILD . 4))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SGRCtrlResult>) ostream)
  "Serializes a message object of type '<SGRCtrlResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SGRCtrlResult>) istream)
  "Deserializes a message object of type '<SGRCtrlResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SGRCtrlResult>)))
  "Returns string type for a message object of type '<SGRCtrlResult>"
  "sagittarius_object_color_detector/SGRCtrlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SGRCtrlResult)))
  "Returns string type for a message object of type 'SGRCtrlResult"
  "sagittarius_object_color_detector/SGRCtrlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SGRCtrlResult>)))
  "Returns md5sum for a message object of type '<SGRCtrlResult>"
  "6cd16eb95067452fc55413e9ecaf8f88")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SGRCtrlResult)))
  "Returns md5sum for a message object of type 'SGRCtrlResult"
  "6cd16eb95067452fc55413e9ecaf8f88")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SGRCtrlResult>)))
  "Returns full string definition for message of type '<SGRCtrlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint8 SUCCESS = 0~%uint8 ERROR = 1~%uint8 PREEMPT = 2~%uint8 PLAN_NOT_FOUND = 3~%uint8 GRASP_FAILD = 4 # 抓空~%~%# 执行结果~%uint8 result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SGRCtrlResult)))
  "Returns full string definition for message of type 'SGRCtrlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint8 SUCCESS = 0~%uint8 ERROR = 1~%uint8 PREEMPT = 2~%uint8 PLAN_NOT_FOUND = 3~%uint8 GRASP_FAILD = 4 # 抓空~%~%# 执行结果~%uint8 result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SGRCtrlResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SGRCtrlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SGRCtrlResult
    (cl:cons ':result (result msg))
))
